config/routes.rb
Feedalgo::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources  :users
  resources  :feeds
  resources  :folders,    :except  => ['update']
  resources  :feed_users, :except  => ['update']

  get 'f/mark_as_read/:id'     => 'feed_entry_users#mark_as_read'
  get 'f/favorite/:id'         => 'feed_entry_users#favorite'
  put   'folders/:id'            => "folders#remove",                        constraints: lambda {|req| req.params.has_key?(:remove)}
  put   'folders/:id'            => "folders#update",                        constraints: lambda {|req| req.params.has_key?(:save)}
  put   'feed_users/:id'         => "feed_users#unsubscribe",                constraints: lambda {|req| req.params.has_key?(:unsubscribe)}
  put   'feed_users/:id'         => "feed_users#update",                     constraints: lambda {|req| req.params.has_key?(:save)}
  get 'f/import'               => 'feeds#import',                          :as => :import
  get 'f/all'                  => 'feeds#all',                             :as => :reader_all
  get 'f/paging/all'           => 'feeds#all_paging',                      :as => :reader_all_paging
  get 'f/all/unread'           => 'feeds#all_unread',                      :as => :reader_all_unread
  get 'f/all/favorites'        => 'feeds#all_favorite',                    :as => :reader_all_favorite
  get 'f/paging/favorites'     => 'feeds#all_favorite_paging',             :as => :reader_all_favorite_paging
  get 'f/folder/:id'           => 'folders#list',                          :as => :reader_folder
  get 'f/folder/toggle/:id'    => 'folders#toggle',                        :as => :toggle_folder
  get 'f/folder/unread/:id'    => 'folders#unread',                        :as => :folder_unread
  get 'f/folder/favorites/:id' => 'folders#favorite',                      :as => :folder_favorite
  get 'f/folder/paging/:id'    => 'folders#list_paging',                   :as => :folder_paging
  get 'f/mark_all'             => 'feed_entry_users#mark_all_read',        :as => :mark_all,        :via => [:post]
  get 'f/mark_all/:id'         => 'feed_entry_users#mark_all_feed_read',   :as => :mark_all_feed,   :via => [:post], :constraints => { :id => /[^\/]*/ }
  get 'f/folder/mark_all/:id'  => 'feed_entry_users#mark_all_folder_read', :as => :mark_all_folder, :via => [:post], :constraints => { :id => /[^\/]*/ }
  get 'f/unread/:id'           => 'feeds#unread',                          :as => :unread,          :constraints => { :id => /[^\/]*/ }
  get 'f/favorites/:id'        => 'feeds#favorite',                        :as => :favorite,        :constraints => { :id => /[^\/]*/ }
  get 'f/paging/:id'           => 'feeds#list_paging',                     :as => :feed_paging,     :constraints => { :id => /[^\/]*/ }
  get 'f/:id'                  => 'feeds#list',                            :as => :reader_feed,     :constraints => { :id => /[^\/]*/ }

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name, :state, :user_id

  validates :name, presence: true

  belongs_to :user
  has_many :feed_user, :dependent => :destroy
  has_many :feeds, :through => :feed_user, select: "feeds.*, feed_users.title, feed_users.folder_id"

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_filter :authenticate_user!
  def list
    @folder = current_user.folders.find(params[:id])
    @entries = current_user.feed_entry_users.where(:feed_id => @folder.feeds).paginate(:page => params[:page])
    respond_to do |format|
      format.js
      format.html
    end
  end

  def list_paging
    @folder = current_user.folders.find(params[:id])
    @entries = current_user.feed_entry_users.where(:feed_id => @folder.feeds).paginate(:page => params[:page])
    respond_to do |format|
      format.js
      format.html
    end
  end

  def unread
    @folder = current_user.folders.find(params[:id])
    @entries = current_user.feed_entry_users.unread.where(:feed_id => @folder.feeds).paginate(:page => params[:page])
    respond_to do |format|
      format.js {render :action => :list}
      format.html {render :action => :list}
    end
  end

  def favorite
    @folder = current_user.folders.find(params[:id])
    @entries = current_user.feed_entry_users.favorite.where(:feed_id => @folder.feeds).paginate(:page => params[:page])
    respond_to do |format|
      format.js {render :action => :list}
      format.html {render :action => :list}
    end
  end

  def toggle
    folder = current_user.folders.find(params[:id])
    folder.state = folder.state ? 0 : 1
    folder.save
    render nothing: true
  end

  def new
    @folder = Folder.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @folder = Folder.new(params[:folder])
    @folder.user_id = current_user.id

    respond_to do |format|
      if @folder.save
        format.js { flash[:notice] = 'The folder was successfully created.' }
      else
        format.js
      end
    end
  end

  def edit
    @folder = current_user.folders.find(params[:id])
  end

  def update
    @folder = current_user.folders.find(params[:id])
    respond_to do |format|
      if @folder.update_attributes(params[:folder])
        format.js {
          flash[:notice] = 'The folder was successfully updated.'
        }
      else
        format.js
      end
    end
  end

  def remove
    @folder = current_user.folders.find(params[:id])
    respond_to do |format|
      if @folder.destroy
        format.js {
          flash[:notice] = "The folder was successfully removed."
        }
      else
        format.js
      end
    end
  end

end

app/views/folders/_form.html.erb
<div id="new-feed" class="modal-dialog">
  <%= simple_form_for(@folder, :remote => true) do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit Folder</h4>
      </div>
      <div class="modal-body">
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :name, :required => true%>
        </div>
      </div>
      <div class="modal-footer">
        <%= image_tag("preloader.gif", :class => 'preloader hide') %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.button :submit, "Delete folder", :class => "btn-danger pull-left", name: "remove", :confirm => "Are you sure you want to remove the folder and unsubscribe to all feeds under it?" %>
        <%= f.button :submit, "Save", :class => "btn-success", name: "save" %>
      </div>
    </div>
  <% end %>
</div>

app/views/folders/create.js.erb
<% if flash.present? %>
  $("#modal-window").modal("hide");
  $(".message-container").remove();
  $("#reader").prepend("<%= escape_javascript(render 'layouts/messages') %>");
<% else %>
  $("#modal-window").html("<%= escape_javascript(render 'form') %>");
<% end %>

app/views/folders/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'form') %>");

app/views/folders/list.html.erb
<%= render "folder_header", :folder => @folder %>
<div id="feed-container">
  <%= render "feed_entries", :entries => @entries, :feed_users => @folder.feeds %>
  <% if @entries.next_page %>
    <span data-next-page="2" data-next-page-url="<%= folder_paging_path(@folder.id) %>" class="next_page">&nbsp;</span>
  <% else %>
    <div class="no_items">There are no more items</div>
  <% end %>
</div>

app/views/folders/list.js.erb
$('#reader').empty();
$('#reader').append('<%= escape_javascript render "folder_header", :folder => @folder %>');
$('#reader').append('<div id="feed-container">');
$('#reader #feed-container').append('<%= escape_javascript render "feed_entries", :entries => @entries, :feed_users => @folder.feeds %>');
attachAccordion();

app/views/folders/list_paging.js.erb
$('#reader #feed-container').append('<%= escape_javascript render "feed_entries", :entries => @entries, :feed_users => @folder.feeds %>');
<% if @entries.next_page %>
  $('#reader #feed-container').append('<span data-next-page="<%= @entries.next_page %>" data-next-page-url="<%= folder_paging_path(@folder.id) %>" class="next_page">&nbsp;</span>');
<% else %>
  $('#reader #feed-container').append('<div class="no_items">There are no more items</div>');
<% end %>
attachAccordion();

app/views/folders/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'form') %>");

app/views/folders/update.js.erb
<% if flash.present? %>
  $("#modal-window").modal("hide");
  $(".message-container").remove();
  $("#reader").prepend("<%= escape_javascript(render 'layouts/messages') %>");
<% else %>
  $("#modal-window").html("<%= escape_javascript(render 'form') %>");
<% end %>