config/routes.rb
Feedalgo::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources  :users
  resources  :feeds
  resources  :folders,    :except  => ['update']
  resources  :feed_users, :except  => ['update']

  get 'f/mark_as_read/:id'     => 'feed_entry_users#mark_as_read'
  get 'f/favorite/:id'         => 'feed_entry_users#favorite'
  put   'folders/:id'            => "folders#remove",                        constraints: lambda {|req| req.params.has_key?(:remove)}
  put   'folders/:id'            => "folders#update",                        constraints: lambda {|req| req.params.has_key?(:save)}
  put   'feed_users/:id'         => "feed_users#unsubscribe",                constraints: lambda {|req| req.params.has_key?(:unsubscribe)}
  put   'feed_users/:id'         => "feed_users#update",                     constraints: lambda {|req| req.params.has_key?(:save)}
  get 'f/import'               => 'feeds#import',                          :as => :import
  get 'f/all'                  => 'feeds#all',                             :as => :reader_all
  get 'f/paging/all'           => 'feeds#all_paging',                      :as => :reader_all_paging
  get 'f/all/unread'           => 'feeds#all_unread',                      :as => :reader_all_unread
  get 'f/all/favorites'        => 'feeds#all_favorite',                    :as => :reader_all_favorite
  get 'f/paging/favorites'     => 'feeds#all_favorite_paging',             :as => :reader_all_favorite_paging
  get 'f/folder/:id'           => 'folders#list',                          :as => :reader_folder
  get 'f/folder/toggle/:id'    => 'folders#toggle',                        :as => :toggle_folder
  get 'f/folder/unread/:id'    => 'folders#unread',                        :as => :folder_unread
  get 'f/folder/favorites/:id' => 'folders#favorite',                      :as => :folder_favorite
  get 'f/folder/paging/:id'    => 'folders#list_paging',                   :as => :folder_paging
  get 'f/mark_all'             => 'feed_entry_users#mark_all_read',        :as => :mark_all,        :via => [:post]
  get 'f/mark_all/:id'         => 'feed_entry_users#mark_all_feed_read',   :as => :mark_all_feed,   :via => [:post], :constraints => { :id => /[^\/]*/ }
  get 'f/folder/mark_all/:id'  => 'feed_entry_users#mark_all_folder_read', :as => :mark_all_folder, :via => [:post], :constraints => { :id => /[^\/]*/ }
  get 'f/unread/:id'           => 'feeds#unread',                          :as => :unread,          :constraints => { :id => /[^\/]*/ }
  get 'f/favorites/:id'        => 'feeds#favorite',                        :as => :favorite,        :constraints => { :id => /[^\/]*/ }
  get 'f/paging/:id'           => 'feeds#list_paging',                     :as => :feed_paging,     :constraints => { :id => /[^\/]*/ }
  get 'f/:id'                  => 'feeds#list',                            :as => :reader_feed,     :constraints => { :id => /[^\/]*/ }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :fetch_feeds_sidebar
  helper_method :xeditable?

  # Assemble the sidebar
  def fetch_feeds_sidebar
    # Skip it if the call is result of an Ajax method
    unless request.xhr?
      if current_user != nil
        @folders = current_user.folders.all
        @feeds = current_user.feeds.ordered.leaf
        @unread = current_user.feed_entries.unread.count(:group => 'feed_entry_users.feed_id')
      end
    end
  end

  def xeditable? object = nil
    true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_all_favorite_header.html.erb
<div class="header">
  <h2>
    <span>Favorites</span>
  </h2>
</div>

app/views/application/_all_header.html.erb
<div class="header">
  <h2>
    <span>All</span>
  </h2>

  <span data-unread-url="<%= reader_all_unread_path()%>" class="unread_url"></span>
  <span data-favorite-url="<%= reader_all_favorite_path()%>" class="favorite_url"></span>
  <span data-read-url="<%= reader_all_path()%>" class="read_url"></span>
  <span data-mark-all-url="<%= mark_all_path()%>" class="mark_all_url"></span>
  <%= render "header_buttons" %>
</div>

app/views/application/_feed_entries.html.erb
<% entries.each do |user_entry| %>
  <%
    feed_entry = user_entry.feed_entry
    feed_user = feed_users.kind_of?(Array) ? feed_users.find {|s| s.id == user_entry.feed.id } : feed_users
  %>

  <%= content_tag(:div, user_entry, :id => "feed_entry_#{user_entry.id}", :class=> "feed_entry") do %>
    <div id="<%= user_entry.id %>" class="feed_bar <%= "unread" if !user_entry.read? %>">
      <span class="date"><%= feed_entry.created_at.today? ? feed_entry.created_at.strftime("%H:%M:%S") : feed_entry.created_at.strftime("%d/%m/%y")  %> </span>
      <span class="feed_icons"><%= render "icons", feed: user_entry %></span>
      <span class="feed_name"><%= feed_user.title %></span>
      <span class="small_title"><%= feed_entry.title.html_safe unless feed_entry.title.nil? %></span>
      <span class="trimed_body"> - <%= raw truncate(strip_tags(feed_entry.body.html_safe), :length => 200) if feed_entry.body %></span>
    </div>
    <div class="full_post">
      <h2 class="title"><%= raw link_to feed_entry.title.html_safe, feed_entry.url, :target => "_blank" unless feed_entry.title.nil? %></h2>
      <div class="authorship">
        From <span class="origin"><%= link_to feed_user.title, feed_entry.url %></span>
        <% if feed_entry.author %>by <span class="author"><%= feed_entry.author %></span><% end %>
      </div>
      <div class="body">
        <%= raw feed_entry.body %>
      </div>
      <div class="actions-bar">
        <span class="feed_icons"><%= render "icons", feed: user_entry %></span>
        <span class="mark-read"><%= link_to user_entry.read? ? "Mark As Unread" : "Mark As Read", :controller => '/feed_entry_users', :action => 'mark_as_read', :id => user_entry.id, :remote => true %></span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/application/_feed_header.html.erb
<div class="header">
  <h2>
    <span><%= feed.title %></span>
    <small class="edit-title"><%= link_to 'Edit', edit_feed_user_path(feed.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></small>
  </h2>

  <span data-unread-url="<%= unread_path(CGI.escape(feed.url))%>" class="unread_url"></span>
  <span data-favorite-url="<%= favorite_path(CGI.escape(feed.url))%>" class="favorite_url"></span>
  <span data-read-url="<%= reader_feed_path(CGI.escape(feed.url))%>" class="read_url"></span>
  <span data-mark-all-url="<%= mark_all_feed_path(CGI.escape(feed.url))%>" class="mark_all_url"></span>
  <%= render "header_buttons" %>
</div>

app/views/application/_folder_header.html.erb
<div class="header">
  <h2>
    <span><%= folder.name %></span>
    <small class="edit-title"><%= link_to 'Edit', edit_folder_path(folder.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></small>
  </h2>

  <span data-unread-url="<%= folder_unread_path(folder)%>" class="unread_url"></span>
  <span data-favorite-url="<%= folder_favorite_path(folder)%>" class="favorite_url"></span>
  <span data-read-url="<%= reader_folder_path(folder)%>" class="read_url"></span>
  <span data-mark-all-url="<%= mark_all_folder_path(folder)%>" class="mark_all_url"></span>
  <%= render "header_buttons" %>
</div>

app/views/application/_header_buttons.html.erb
    <div class="btn-toolbar">
      <div class="btn-group">
        <button class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
          Show ...
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="#" id="showAll">All</a></li>
            <li><a href="#" id="showUnread">Unread</a></li>
            <li><a href="#" id="showFavorite">Favorites</a></li>
        </ul>
      </div>
      <div class="btn-group">
        <button class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
          Mark all as read
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="#" class="mark" id="all">All items</a></li>
            <li><a href="#" class="mark" id="day">Items older than one day</a></li>
            <li><a href="#" class="mark" id="week">Items older than one week</a></li>
            <li><a href="#" class="mark" id="month">Items older than one month</a></li>
        </ul>
      </div>
    </div>

app/views/application/_icons.html.erb
<% if feed.favorite %>
  <%= link_to content_tag(:span, ' ', :class => "icon-star yellow"), {:controller => "/feed_entry_users", :action => "favorite", :id => feed.id}, remote: true, :class => "feed_icon" %>
<% else %>
  <%= link_to content_tag(:span, ' ', :class => "icon-star-empty yellow"), {:controller => "/feed_entry_users", :action => "favorite", :id => feed.id}, remote: true, :class => "feed_icon" %>
<% end %>

app/views/application/_list_all_favorite_items.html.erb
<%= render "all_favorite_header" %>
<div id="feed-container">
  <%= render "feed_entries", :entries => @entries, :feed_users => @feeds %>
  <% if @entries.next_page %>
    <span data-next-page="2" data-next-page-url="<%= reader_all_favorite_paging_path() %>" class="next_page">&nbsp;</span>
  <% else %>
    <div class="no_items">There are no more items</div>
  <% end %>
</div>

<script type="test/javascript">
  attachAccordion();
</script>

app/views/application/_list_all_items.html.erb
<%= render "all_header" %>
<div id="feed-container">
  <%= render "feed_entries", :entries => @entries, :feed_users => @feeds %>
  <% if @entries.next_page %>
    <span data-next-page="2" data-next-page-url="<%= reader_all_paging_path() %>" class="next_page">&nbsp;</span>
  <% else %>
    <div class="no_items">There are no more items</div>
  <% end %>
</div>

<script type="test/javascript">
  attachAccordion();
</script>

app/views/application/_list_item.html.erb
<%= render "feed_header", :feed => @feed %>
<div id="feed-container">
  <%= render "feed_entries", :entries => @entries, :feed_users => @feed_users %>
  <% if @entries.next_page %>
    <span data-next-page="2" data-next-page-url="<%= feed_paging_path(CGI.escape(@feed.url)) %>" class="next_page">&nbsp;</span>
  <% else %>
    <div class="no_items">There are no more items</div>
  <% end %>
</div>

<script type="test/javascript">
  attachAccordion();
  update_count('<%= @feed.id %>', '<%= feed_count.zero? ? nil : feed_count %>');
</script>