config/routes.rb
Feedalgo::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources  :users
  resources  :feeds
  resources  :folders,    :except  => ['update']
  resources  :feed_users, :except  => ['update']

  get 'f/mark_as_read/:id'     => 'feed_entry_users#mark_as_read'
  get 'f/favorite/:id'         => 'feed_entry_users#favorite'
  put   'folders/:id'            => "folders#remove",                        constraints: lambda {|req| req.params.has_key?(:remove)}
  put   'folders/:id'            => "folders#update",                        constraints: lambda {|req| req.params.has_key?(:save)}
  put   'feed_users/:id'         => "feed_users#unsubscribe",                constraints: lambda {|req| req.params.has_key?(:unsubscribe)}
  put   'feed_users/:id'         => "feed_users#update",                     constraints: lambda {|req| req.params.has_key?(:save)}
  get 'f/import'               => 'feeds#import',                          :as => :import
  get 'f/all'                  => 'feeds#all',                             :as => :reader_all
  get 'f/paging/all'           => 'feeds#all_paging',                      :as => :reader_all_paging
  get 'f/all/unread'           => 'feeds#all_unread',                      :as => :reader_all_unread
  get 'f/all/favorites'        => 'feeds#all_favorite',                    :as => :reader_all_favorite
  get 'f/paging/favorites'     => 'feeds#all_favorite_paging',             :as => :reader_all_favorite_paging
  get 'f/folder/:id'           => 'folders#list',                          :as => :reader_folder
  get 'f/folder/toggle/:id'    => 'folders#toggle',                        :as => :toggle_folder
  get 'f/folder/unread/:id'    => 'folders#unread',                        :as => :folder_unread
  get 'f/folder/favorites/:id' => 'folders#favorite',                      :as => :folder_favorite
  get 'f/folder/paging/:id'    => 'folders#list_paging',                   :as => :folder_paging
  get 'f/mark_all'             => 'feed_entry_users#mark_all_read',        :as => :mark_all,        :via => [:post]
  get 'f/mark_all/:id'         => 'feed_entry_users#mark_all_feed_read',   :as => :mark_all_feed,   :via => [:post], :constraints => { :id => /[^\/]*/ }
  get 'f/folder/mark_all/:id'  => 'feed_entry_users#mark_all_folder_read', :as => :mark_all_folder, :via => [:post], :constraints => { :id => /[^\/]*/ }
  get 'f/unread/:id'           => 'feeds#unread',                          :as => :unread,          :constraints => { :id => /[^\/]*/ }
  get 'f/favorites/:id'        => 'feeds#favorite',                        :as => :favorite,        :constraints => { :id => /[^\/]*/ }
  get 'f/paging/:id'           => 'feeds#list_paging',                     :as => :feed_paging,     :constraints => { :id => /[^\/]*/ }
  get 'f/:id'                  => 'feeds#list',                            :as => :reader_feed,     :constraints => { :id => /[^\/]*/ }

end

app/views/layouts/_messages.html.erb
<div class="message-container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to "Feedalgo", root_path, :class => 'navbar-brand' %>
</div>
<nav class="collapse navbar-collapse">
  <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li><%= link_to t('Import'), import_path %></li>
    <% else %>
    <% end %>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li><%= link_to t('Sign out'), destroy_user_session_path, :method => 'delete' %></li>
    <% else %>
      <li><%= link_to t('Sign up'), new_user_registration_path %></li>
      <li><%= link_to t('Login'), new_user_session_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_sidebar.html.erb
<ul class="inner-sidebar">
  <li>
    <%= content_tag(:span, " " , :class => "pull-left small-folder orange icon-rss") %>
    <%=  link_to "All", reader_all_path(), :remote => true %>
  </li>
  <li>
    <%= content_tag(:span, " " , :class => "pull-left small-star yellow icon-star") %>
    <%=  link_to "Favorites", reader_all_favorite_path(), :remote => true %>
  </li>
  <%= content_tag_for(:li, @folders) do |folder| %>
    <%= content_tag(:span, " " , :class => "pull-left small-folder black icon-folder-" + (folder.state ? "open" : "close")) %>
    <%= link_to folder.name, reader_folder_path(folder), :remote => true %>
      <ul class="nav <%= folder.state ? "open" : "closed" %>">
        <% folder.feeds.each do |feed|%>
          <li class="item" id="feed_<%= feed.id%>"><%= render "layouts/sidebar_feed", :feed => feed %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
  <% @feeds.each do |feed|%>
    <li class="item" id="feed_<%= feed.id%>"><%= render "layouts/sidebar_feed", :feed => feed %></li>
  <% end %>
</ul>

app/views/layouts/_sidebar_feed.html.erb
<%= content_tag(:span, image_tag(feed.favicon, :width => 16, :height => 16, :class => "favicon"), :class => "pull-left") unless feed.favicon.nil? %>
<%= content_tag(:span, image_tag("feed.png", :width => 16, :height => 16, :class => "favicon"), :class => "pull-left") if feed.favicon.nil? %>
<%= content_tag(:span, @unread[feed.id], :class=> "badge pull-right spaced-badge") %>
<div class="feed-name"><%= link_to feed.title, reader_feed_path(CGI.escape(feed.url)), :remote => true %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "Feedalgo | An open source RSS reader"  %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "An open source RSS reader" %>">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header id="main-header" class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <%= render 'layouts/navigation' %>
      </div>
    </header>

    <section id="main" class="container-fluid">
        <div class="row">
          <% if signed_in? %>
            <div id="sidebar" class="scrollable col-xs-2">
              <%= render 'layouts/sidebar' %>
            </div>
            <div id="toolbar" class="col-xs-2">

              <div class="btn-group dropup">
                <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                  Add
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><%= link_to content_tag(:span, " " , :class => "pull-left icon-plus") + 'Add subscription', new_feed_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %></li>
                    <li><%= link_to content_tag(:span, " " , :class => "pull-left small-folder icon-folder-open") + 'Add folder', new_folder_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %></li>
                </ul>
              </div>
            </div>
            <div id="reader" class="scrollable col-xs-10">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          <% else %>
            <div id="reader" class="scrollable col-xs-12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          <% end %>
        </div>
    </section>
    <div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
  </body>
</html>